### ISSUE TITLE
Line Breaks

### ISSUE THREAD

**Issue by Visiblink** [michael-lazar/gemini-portal#4]
This is a strange issue. I use the gemini portal every day with the Lynx browser. Lynx doesn't have built-in Gemini support (I asked on their mailing list, but it's never been added) and the portal is a great way to keep using Lynx as an all-in-one browser.

Here's the issue: the gemini portal reproduces line breaks in gemtext faithfully when using it with Firefox. However, it produces a "wall of text" in Lynx. 

Here's a site that demonstrates the issue really well: gemini://idiomdrottning.org/occams-turtles

![image](https://github.com/michael-lazar/gemini-portal/assets/82686470/d92d294b-74dd-4c38-864d-d1a4679e5d42)

![Screenshot_2023-08-12_09-01-54](https://github.com/michael-lazar/gemini-portal/assets/82686470/ae64f5bd-3327-469b-a178-41694c075ef5)

It's probably a Lynx issue, but if there's any way to fix it, I'd really appreciate it. Big thanks for this and pygopherd!

**Comment by michael-lazar** [comment]
Hi, I like to support Lynx and other niche web environments so thanks for posting this!

I'm using a CSS rule `white-space: pre-wrap` for the whitespace in gemini, and I don't think Lynx recognizes that rule (or any CSS at all?)

I just tried replacing the `\n` newlines with `<br>` tags and I think it looks like that solved it. I also had to go into my Lynx settings and disable `COLLAPSE_BR_TAGS` as described here: 

https://unix.stackexchange.com/questions/170551/force-lynx-or-elinks-to-interpret-spaces-and-line-breaks

<img width="762" alt="Screen Shot 2023-08-12 at 9 33 49 PM" src="https://github.com/michael-lazar/gemini-portal/assets/5026795/f33d5660-5ba1-4e74-a3ff-8e6d36d80f06">

**Comment by Visiblink** [comment]
Thank you for making the change and looking into the Lynx setting. It worked perfectly! 

For anyone reading this and using Debian, you need to go into /etc/lynx/lynx.cfg and uncomment COLLAPSE_BR_TAGS:TRUE and then change it to COLLAPSE_BR_TAGS:FALSE
